/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Auxiliares.Control;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ziconos.Advertencia;

/**
 *
 * @author WjhonB
 */
public class ControlaHora extends javax.swing.JFrame {

    private Advertencia icono;
    public ControlaHora() {
        initComponents();
        this.getContentPane().setBackground(new Color(0,0,0));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        icono=new Advertencia();
        this.addWindowListener ( new WindowAdapter() { 
        public void windowClosing(WindowEvent e) { 
        new Control().cerrarApp();
        } 
        }); 
        
          try{
        this.setIconImage(new ImageIcon(getClass().getResource("/zimagenes/carga.jpg")).getImage());
        }catch(Exception e){
        System.out.println(e.getMessage());
        }
          this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menu = new javax.swing.JComboBox<>();
        btnIng = new javax.swing.JButton();
        btnSal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIENVENIDO(A) A CONTROL DE HORA:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("POR FAVOR SELECCIONE");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DONDE DESEA INGRESAR:");

        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCENTES", "ESTUDIANTES", "ADMINISTRATIVOS" }));
        menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                menuKeyTyped(evt);
            }
        });

        btnIng.setText("INGRESAR");
        btnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngActionPerformed(evt);
            }
        });

        btnSal.setText("SALIR");
        btnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnIng, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btnSal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIng)
                    .addComponent(btnSal))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuKeyTyped
        char tecla= evt.getKeyChar();
        if(tecla== KeyEvent.VK_ENTER){
            btnIng.doClick();
        }
    }//GEN-LAST:event_menuKeyTyped

    private void btnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngActionPerformed
        String sep = System.getProperty("line.separator");
        Calendar calendario = GregorianCalendar.getInstance();
        Date fecha1 = calendario.getTime();
        SimpleDateFormat formato1= new SimpleDateFormat("yyyy-MM-dd 00:00:00");
        SimpleDateFormat formato2= new SimpleDateFormat("yyyy-MM-dd 23:59:59");
       
        if((menu.getSelectedItem().toString()).equals("")){
            JOptionPane.showMessageDialog(this, "No selecciono una Base de Datos seleccione porfavor","",JOptionPane.WARNING_MESSAGE,icono);
        }
        else{
            if((menu.getSelectedItem().toString()).equals("DOCENTES")){
                   this.setVisible(false);
                    ControlHora.ControlarHora ch=new ControlHora.ControlarHora();
                    ch.mostrardatos1(formato1.format(fecha1),formato2.format(fecha1));
                    ch.setVisible(true);
            }
            if((menu.getSelectedItem().toString()).equals("ESTUDIANTES")){
                   this.setVisible(false);
                    ControlHora.ControlarHoraEst ch=new ControlHora.ControlarHoraEst();
                    ch.mostrardatos1(formato1.format(fecha1),formato2.format(fecha1));
                    ch.setVisible(true);
            }
            if((menu.getSelectedItem().toString()).equals("ADMINISTRATIVOS")){
                   this.setVisible(false);
                    ControlHora.ControlarHoraAdm ch=new ControlHora.ControlarHoraAdm();
                    ch.mostrardatos1(formato1.format(fecha1),formato2.format(fecha1));
                    ch.setVisible(true);
            }
             

        }
    }//GEN-LAST:event_btnIngActionPerformed

    private void btnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalActionPerformed
        new Control().cerrarApp();
    }//GEN-LAST:event_btnSalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIng;
    private javax.swing.JButton btnSal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox<String> menu;
    // End of variables declaration//GEN-END:variables
}
